# Generated by Django 3.1 on 2020-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
